//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *BillingScope) DeepCopyInto(out *BillingScope) {
	*out = *in
	out.MaxFinancialBudget = in.MaxFinancialBudget.DeepCopy()
}

func (in *BillingScope) DeepCopy() *BillingScope {
	if in == nil {
		return nil
	}
	out := new(BillingScope)
	in.DeepCopyInto(out)
	return out
}

func (in *DetectionCriteria) DeepCopyInto(out *DetectionCriteria) {
	*out = *in
	if in.OTel != nil {
		in, out := &in.OTel, &out.OTel
		*out = new(OTelCriteria)
		**out = **in
	}
	if in.Semantic != nil {
		in, out := &in.Semantic, &out.Semantic
		*out = new(SemanticCriteria)
		**out = **in
	}
}

func (in *DetectionCriteria) DeepCopy() *DetectionCriteria {
	if in == nil {
		return nil
	}
	out := new(DetectionCriteria)
	in.DeepCopyInto(out)
	return out
}

func (in *FaultConfig) DeepCopyInto(out *FaultConfig) { *out = *in }

func (in *FaultConfig) DeepCopy() *FaultConfig {
	if in == nil {
		return nil
	}
	out := new(FaultConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *LivelockPolicy) DeepCopyInto(out *LivelockPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *LivelockPolicy) DeepCopy() *LivelockPolicy {
	if in == nil {
		return nil
	}
	out := new(LivelockPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *LivelockPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LivelockPolicyList) DeepCopyInto(out *LivelockPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LivelockPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LivelockPolicyList) DeepCopy() *LivelockPolicyList {
	if in == nil {
		return nil
	}
	out := new(LivelockPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *LivelockPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LivelockPolicySpec) DeepCopyInto(out *LivelockPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Detection.DeepCopyInto(&out.Detection)
	in.Remediation.DeepCopyInto(&out.Remediation)
}

func (in *LivelockPolicySpec) DeepCopy() *LivelockPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LivelockPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LivelockPolicyStatus) DeepCopyInto(out *LivelockPolicyStatus) {
	*out = *in
	if in.LastDetection != nil {
		in, out := &in.LastDetection, &out.LastDetection
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LivelockPolicyStatus) DeepCopy() *LivelockPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(LivelockPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelLimit) DeepCopyInto(out *ModelLimit) { *out = *in }

func (in *ModelLimit) DeepCopy() *ModelLimit {
	if in == nil {
		return nil
	}
	out := new(ModelLimit)
	in.DeepCopyInto(out)
	return out
}

func (in *OTelCriteria) DeepCopyInto(out *OTelCriteria) { *out = *in }

func (in *OTelCriteria) DeepCopy() *OTelCriteria {
	if in == nil {
		return nil
	}
	out := new(OTelCriteria)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
	if in.FaultConfig != nil {
		in, out := &in.FaultConfig, &out.FaultConfig
		*out = new(FaultConfig)
		**out = **in
	}
}

func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SemanticCriteria) DeepCopyInto(out *SemanticCriteria) { *out = *in }

func (in *SemanticCriteria) DeepCopy() *SemanticCriteria {
	if in == nil {
		return nil
	}
	out := new(SemanticCriteria)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetRef) DeepCopyInto(out *TargetRef) { *out = *in }

func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

func (in *TokenQuota) DeepCopyInto(out *TokenQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TokenQuota) DeepCopy() *TokenQuota {
	if in == nil {
		return nil
	}
	out := new(TokenQuota)
	in.DeepCopyInto(out)
	return out
}

func (in *TokenQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TokenQuotaList) DeepCopyInto(out *TokenQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TokenQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TokenQuotaList) DeepCopy() *TokenQuotaList {
	if in == nil {
		return nil
	}
	out := new(TokenQuotaList)
	in.DeepCopyInto(out)
	return out
}

func (in *TokenQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TokenQuotaSpec) DeepCopyInto(out *TokenQuotaSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.BillingScope.DeepCopyInto(&out.BillingScope)
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make([]ModelLimit, len(*in))
		copy(*out, *in)
	}
}

func (in *TokenQuotaSpec) DeepCopy() *TokenQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(TokenQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TokenQuotaStatus) DeepCopyInto(out *TokenQuotaStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.NextRenewal != nil {
		in, out := &in.NextRenewal, &out.NextRenewal
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TokenQuotaStatus) DeepCopy() *TokenQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(TokenQuotaStatus)
	in.DeepCopyInto(out)
	return out
}
