apiVersion: v1
kind: Service
metadata:
  name: {{ include "kovern.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kovern.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      name: webhook
    - port: {{ .Values.otlp.port }}
      targetPort: {{ .Values.otlp.port }}
      name: otlp
  selector:
    {{- include "kovern.selectorLabels" . | nindent 4 }}
